// <auto-generated />
using System;
using DistributedCachingSampleApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DistributedCachingSampleApp.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220130065644_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.1");

            modelBuilder.Entity("DistributedCachingSampleApp.DomainModel.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Mark")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Customer");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Ahmed",
                            LastName = "Qaid",
                            Mark = 20
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Ali",
                            LastName = "Mohammed",
                            Mark = 30
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Saud",
                            LastName = "Alfadhli",
                            Mark = 40
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
